name: deploy-latest

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      uses: docker/login-action@v2.2.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ secrets.NCLOUD_CONTAINER_REGISTRY_URL }}
        # Username used to log against the Docker registry
        username: ${{ secrets.NCLOUD_ACCESS_KEY_ID }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.NCLOUD_ACCESS_KEY_SECRET }}
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: false # optional, default is auto
        # Log out from the Docker registry at the end of a job
        logout: true # optional, default is true

    - name: Build and push image
      run: cd deploy/ncloud; ./push-image-latest.sh
      env:
        NCLOUD_CONTAINER_REGISTRY_URL: ${{ secrets.NCLOUD_CONTAINER_REGISTRY_URL }}
